### ISSUE TITLE
SG tag may have an extra element on the front and back of the array

### ISSUE THREAD

**Issue by kvg** [broadinstitute/longbow#17]
Right now, the SG tag appears to be annotating an extra region of the state sequence on the front and back of the array.  For example, for this read,

```
m64020_201213_022403/23/ccs/23_807/10x_Adapter-3p_Adapter ... SG:Z:10x_Adapter:0-22,random:23-777,Poly_A:778-807,3p_Adapter:808-832
```
the state sequence says the first 22 bases should be the 10x_Adapter and the last 24 bases should be the 3p_Adapter.  But the read actually contains this:

![m64020_201213_022403_23_ccs_23_807_10x_Adapter-3p_Adapter](https://user-images.githubusercontent.com/2800374/107137642-7f229a00-68dc-11eb-80e5-2a393ef47b2b.png)

To compensate for now, I've written the `inspect` tool to ignore the first and last array elements of the SG tag (https://github.com/broadinstitute/annmas/blob/3ddb711b1bf5fb926c59cdc9f264e89075976e25/src/annmas/inspect/command.py#L180).  But it does technically mean that the base ranges specified by the SG tag don't actually match up to the read sequence.  We should fix this so that they do indeed match, and then change `inspect` so that it no longer has to do any trimming on the SG array.

**Comment by jonn-smith** [comment]
Yeah - this is a purposeful decision based on our last conversation - to keep the sequence information but remove the unnecessary pieces (the leading and trailing adapters - the 10x and 3p segments).

I left in the whole array so I could account for the elements in later processing.  

I can change it back to keep all elements of the split relatively easily.

**Comment by kvg** [comment]
Sorry, I don't think I was clear in what I was thinking.  What I mean is that it'd be useful to 

1. Have the SG annotations specify exactly how the read query sequence should be classified, and have that work for both the results of `annmas annotate` and `annmas segment`.  This would allow us to use `annmas inspect` for both output types and verify that reads are segmented properly without having to rerun the annotation model, since the annotation model output is already stored in the SG tag.
2. Trim off the extraneous adapters in a way that is compatible with the isoseq3 `tag` command (https://github.com/PacificBiosciences/IsoSeq/blob/master/isoseq-deduplication.md).  I *think* that means removing the 10x_Adapter, MAS-seq adapters, and 3p_Adapter, but *not* the poly-A tail (which would be removed by the isoseq3 `refine` command).

The image below depicts what I we should be doing on an example read (I've drawn just the first two segments).  Here, the output of `segment` would only be the transcriptomic portions of the read (and the CBC+UMI, which would be tagged and stripped off by the isoseq3 tools).

![demo](https://user-images.githubusercontent.com/2800374/107372160-1c372b80-6ab3-11eb-83bd-fa027e7211f3.png)

This would also remove some useful information, like the MAS-seq delimiters we see on either side of the read.  Those could be stored in separate tags, say, "SL" and "SR" or something like that.

What do you think?

**Comment by jonn-smith** [comment]
That sounds fine to me - currently the code is producing the output for [1] already, so that's good to go. 

For the current pipeline, updating the segmentation like this will require a modification of the 10x tool.  This shouldn't be a problem, but it'll take some time to make sure it's still the right thing.

I like the tags for the other adapters.
