### ISSUE TITLE
How to get barcode and umi file after extract step ?

### ISSUE THREAD

**Issue by hmyh1202** [broadinstitute/longbow#187]
Hi, :

   I am new in this filed of MAS-seq, and I want to do calculate the RPKM value of each barcode cluster data. And how to get  the barcode and umi file after extract step?
  And some correct would needed for the barcode and UMI ?
Thank you !

**Comment by jonn-smith** [comment]
Hi @hmyh1202 

There are no tools included in longbow to calculate the RPKM values. 

Please make sure you're using the latest version of longbow.  With that version, the models have to be specified by the base library prep AND the MAS-seq array.  This allows for more flexibility across experiments.  With the latest models, a raw barcode and raw UMI are produced by the `segment` step in read tags (UMI: `ZU`, CBC: `CR` ).

I'd recommend using the `longbow correct` step for cell barcode correction.  You will need the cell barcode whitelist for your library prep.  This step is very memory intensive, so it should only be run on a single core.

You may use `longbow correct_umi` to do UMI correction, but you will need gene/transcript assignments prior to running this step.

**Comment by hmyh1202** [comment]
Got  it !

Does the UMI must be corrected ?

Many paper did do barcode correction based on barcode white list file.

Thank you .
