### ISSUE TITLE
Need conda environment setup

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/longbow#67]
While we rely on the built-in venv commands in python, we should also support conda environments.

**Comment by Magdoll** [comment]
Ideally we'd like something like
```
conda install -c bioconda longbow
```

A secondary or perhaps more flexible interim option is a .yml file
ex: for [SQANTI3](https://github.com/ConesaLab/SQANTI3) we use a [.yml](https://github.com/ConesaLab/SQANTI3/blob/master/SQANTI3.conda_env.yml)

Then to install they do:

```
git clone https://github.com/ConesaLab/SQANTI3.git
cd SQANTI3
conda env create -f SQANTI3.conda_env.yml
source activate SQANTI3.env
```

**Comment by kvg** [comment]
Done! Longbow can now be installed directly from pip (couldn't make a conda package as there are dependencies that are only available through pip).  Alternatively, one can use the `longbow.conda_env.yml` conda environment definition precisely as suggested above.
